"""empty message

Revision ID: 17e0f3dfff97
Revises: f3f7226730e7
Create Date: 2024-11-19 11:01:51.496580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e0f3dfff97'
down_revision = 'f3f7226730e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=False, server_default= 'unknown'))

    op.alter_column('planet', 'climate', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('climate')

    # ### end Alembic commands ###
